services:
  - type: web
    name: subtitle-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "Starting scraper to build database..."
      python scraper.py
      echo "Scraper finished."
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    healthCheckPath: /healthz
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: OWNER_ID
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
