services:
  - type: web
    name: subtitle-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "Starting scraper to build database..."
      python scraper.py || echo "Scraper failed, using existing db.json if available"
      echo "Build complete."
    startCommand: gunicorn app:app -k uvicorn.workers.UvicornWorker -w 1 --timeout 120 --keep-alive 2
    healthCheckPath: /healthz
    autoDeploy: false
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: OWNER_ID
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: "production"
      - key: SCRAPER_MAX_PAGES
        value: "15"
      - key: SCRAPER_DELAY
        value: "1.5"
