services:
  - type: web
    name: subtitle-bot
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: LOG_TOPIC_ID
        sync: false
