# .github/workflows/scraper.yml
name: Daily Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: 'jules-bot-fix'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if database changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update subtitle database"
          file_pattern: "db.json series_db.json"
          commit_author: GitHub Actions <actions@github.com>
